"use client"

import { useState } from "react"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Calendar } from "@/components/ui/calendar"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { CalendarIcon, Loader2, DollarSign } from "lucide-react"
import { format } from "date-fns"
import { apiService } from "@/lib/api"
import { useToast } from "@/hooks/use-toast"
import { cn } from "@/lib/utils"

interface ReceiptCreationDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  dealId: string
  clientId: string
  onSuccess?: () => void
}

export function ReceiptCreationDialog({
  open,
  onOpenChange,
  dealId,
  clientId,
  onSuccess,
}: ReceiptCreationDialogProps) {
  const { toast } = useToast()
  const [loading, setLoading] = useState(false)
  const [amount, setAmount] = useState("")
  const [method, setMethod] = useState<"Cash" | "Bank">("Cash")
  const [date, setDate] = useState<Date>(new Date())
  const [notes, setNotes] = useState("")
  const [referenceNumber, setReferenceNumber] = useState("")
  const [manualUniqueId, setManualUniqueId] = useState("")

  const handleSubmit = async () => {
    if (!amount || parseFloat(amount) <= 0) {
      toast({
        title: "Validation Error",
        description: "Please enter a valid payment amount",
        variant: "destructive",
      })
      return
    }

    try {
      setLoading(true)
      const response: any = await apiService.receipts.create({
        dealId,
        clientId,
        amount: parseFloat(amount),
        method,
        date: date.toISOString(),
        notes: notes || null,
        referenceNumber: referenceNumber.trim() || undefined,
        manualUniqueId: manualUniqueId.trim() || undefined,
      })

      if (response?.data?.success || response?.success) {
        toast({
          title: "Success",
          description: `Receipt created successfully. ${response.data?.totalAllocated || 0} allocated to installments.`,
        })
        setAmount("")
        setNotes("")
        setReferenceNumber("")
        setDate(new Date())
        onOpenChange(false)
        onSuccess?.()
      } else {
        throw new Error(response?.error || "Failed to create receipt")
      }
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message || "Failed to create receipt",
        variant: "destructive",
      })
    } finally {
      setLoading(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>Record Payment (Create Receipt)</DialogTitle>
          <DialogDescription>
            Create a receipt for payment received. The system will automatically allocate the amount to installments using FIFO.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4 py-4">
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="systemId">System ID (Auto-generated)</Label>
              <Input
                id="systemId"
                value="Will be generated on save"
                disabled
                className="bg-muted text-muted-foreground"
              />
              <p className="text-xs text-muted-foreground">This ID is automatically generated by the system</p>
            </div>
            <div className="space-y-2">
              <Label htmlFor="manualUniqueId">Manual Unique ID (Optional)</Label>
              <Input
                id="manualUniqueId"
                value={manualUniqueId}
                onChange={(e) => setManualUniqueId(e.target.value)}
                placeholder="Enter custom unique ID (optional)"
              />
              <p className="text-xs text-muted-foreground">Optional: Enter a custom unique identifier</p>
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="amount">Amount Received *</Label>
            <Input
              id="amount"
              type="number"
              min="0"
              step="0.01"
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
              placeholder="Enter amount"
              required
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="method">Payment Method *</Label>
            <Select value={method} onValueChange={(value: "Cash" | "Bank") => setMethod(value)}>
              <SelectTrigger id="method">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="Cash">Cash</SelectItem>
                <SelectItem value="Bank">Bank</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label htmlFor="date">Payment Date *</Label>
            <Popover>
              <PopoverTrigger asChild>
                <Button
                  id="date"
                  variant="outline"
                  className={cn(
                    "w-full justify-start text-left font-normal",
                    !date && "text-muted-foreground"
                  )}
                >
                  <CalendarIcon className="mr-2 h-4 w-4" />
                  {date ? format(date, "PPP") : "Pick a date"}
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0">
                <Calendar mode="single" selected={date} onSelect={(d) => d && setDate(d)} initialFocus />
              </PopoverContent>
            </Popover>
          </div>
          <div className="space-y-2">
            <Label htmlFor="referenceNumber">Reference/Cheque No (Optional)</Label>
            <Input
              id="referenceNumber"
              value={referenceNumber}
              onChange={(e) => setReferenceNumber(e.target.value)}
              placeholder="Enter reference or cheque number"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="notes">Notes (Optional)</Label>
            <Textarea
              id="notes"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Additional notes about this payment..."
              rows={3}
            />
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={loading}>
            Cancel
          </Button>
          <Button onClick={handleSubmit} disabled={loading || !amount}>
            {loading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Creating...
              </>
            ) : (
              <>
                <DollarSign className="mr-2 h-4 w-4" />
                Create Receipt
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

