/**
 * Entity Column Registry
 * Single source of truth for all table columns, filters, and exports across the ERP.
 * 
 * Columns defined here drive:
 * - Table rendering
 * - Advanced filters
 * - Download Report column selection
 * - Export format compatibility
 * - Role-based visibility
 */

export type ExportFormat = "csv" | "excel" | "pdf" | "word";
export type DataType = "string" | "number" | "date" | "boolean" | "currency" | "percentage" | "relation";
export type ColumnGroup = "Basic" | "Contact" | "Financial" | "Status" | "Relationships" | "System" | "Metadata";

export interface EntityColumnDefinition {
  /** Unique column key (matches data field) */
  key: string;
  /** Display label */
  label: string;
  /** Entity this column belongs to */
  entity: string;
  /** Logical group for UI organization */
  group: ColumnGroup;
  /** Data type for formatting/validation */
  data_type: DataType;
  /** Can this column be exported? */
  exportable: boolean;
  /** Which export formats support this column */
  formats: ExportFormat[];
  /** Roles that can see/export this column (empty = all roles) */
  roles: string[];
  /** Can this column be used in filters? */
  filterable: boolean;
  /** Can this column be sorted? */
  sortable: boolean;
  /** Visible by default in table views */
  default_visible: boolean;
  /** Column width hint (for table rendering) */
  width?: number;
  /** Format function for display/export */
  format?: (value: any, row?: any) => string;
  /** Relation field path (e.g., "assignedAgent.username") */
  relation_path?: string;
  /** Tooltip/help text */
  description?: string;
}

/**
 * Column Registry
 * All columns for all entities must be registered here.
 */
export const ENTITY_COLUMN_REGISTRY: Record<string, EntityColumnDefinition[]> = {
  lead: [
    {
      key: "tid",
      label: "TID",
      entity: "lead",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 100,
    },
    {
      key: "leadCode",
      label: "Lead Code",
      entity: "lead",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "name",
      label: "Lead Name",
      entity: "lead",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf", "word"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 200,
    },
    {
      key: "email",
      label: "Email",
      entity: "lead",
      group: "Contact",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 200,
    },
    {
      key: "phone",
      label: "Phone",
      entity: "lead",
      group: "Contact",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
    {
      key: "status",
      label: "Status",
      entity: "lead",
      group: "Status",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf", "word"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "priority",
      label: "Priority",
      entity: "lead",
      group: "Status",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: false,
      width: 100,
    },
    {
      key: "source",
      label: "Source",
      entity: "lead",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "temperature",
      label: "Temperature",
      entity: "lead",
      group: "Status",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: false,
      width: 100,
    },
    {
      key: "interest",
      label: "Interest",
      entity: "lead",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
    {
      key: "budgetMin",
      label: "Budget Min",
      entity: "lead",
      group: "Financial",
      data_type: "currency",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: false,
      width: 120,
    },
    {
      key: "budgetMax",
      label: "Budget Max",
      entity: "lead",
      group: "Financial",
      data_type: "currency",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: false,
      width: 120,
    },
    {
      key: "assignedAgent",
      label: "Assigned Agent",
      entity: "lead",
      group: "Relationships",
      data_type: "relation",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: false,
      default_visible: true,
      width: 150,
      relation_path: "assignedAgent.username",
      format: (v) => v?.username || v?.name || "",
    },
    {
      key: "assignedDealer",
      label: "Assigned Dealer",
      entity: "lead",
      group: "Relationships",
      data_type: "relation",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: false,
      default_visible: false,
      width: 150,
      relation_path: "assignedDealer.name",
      format: (v) => v?.name || "",
    },
    {
      key: "createdAt",
      label: "Created Date",
      entity: "lead",
      group: "System",
      data_type: "date",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
    {
      key: "updatedAt",
      label: "Updated Date",
      entity: "lead",
      group: "System",
      data_type: "date",
      exportable: true,
      formats: ["csv", "excel"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: false,
      width: 150,
    },
    {
      key: "id",
      label: "ID",
      entity: "lead",
      group: "System",
      data_type: "string",
      exportable: false,
      formats: [],
      roles: [],
      filterable: false,
      sortable: false,
      default_visible: false,
    },
  ],
  client: [
    {
      key: "tid",
      label: "TID",
      entity: "client",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 100,
    },
    {
      key: "clientCode",
      label: "Client Code",
      entity: "client",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "name",
      label: "Name",
      entity: "client",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf", "word"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 200,
    },
    {
      key: "email",
      label: "Email",
      entity: "client",
      group: "Contact",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 200,
    },
    {
      key: "phone",
      label: "Phone",
      entity: "client",
      group: "Contact",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
    {
      key: "status",
      label: "Status",
      entity: "client",
      group: "Status",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf", "word"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "clientType",
      label: "Type",
      entity: "client",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "city",
      label: "City",
      entity: "client",
      group: "Contact",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: false,
      width: 150,
    },
    {
      key: "assignedDealer",
      label: "Assigned Dealer",
      entity: "client",
      group: "Relationships",
      data_type: "relation",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: false,
      default_visible: true,
      width: 150,
      relation_path: "assignedDealer.name",
      format: (v) => v?.name || "",
    },
    {
      key: "createdAt",
      label: "Created Date",
      entity: "client",
      group: "System",
      data_type: "date",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
  ],
  dealer: [
    {
      key: "tid",
      label: "TID",
      entity: "dealer",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 100,
    },
    {
      key: "dealerCode",
      label: "Dealer Code",
      entity: "dealer",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "name",
      label: "Name",
      entity: "dealer",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf", "word"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 200,
    },
    {
      key: "email",
      label: "Email",
      entity: "dealer",
      group: "Contact",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 200,
    },
    {
      key: "phone",
      label: "Phone",
      entity: "dealer",
      group: "Contact",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
    {
      key: "isActive",
      label: "Active",
      entity: "dealer",
      group: "Status",
      data_type: "boolean",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 100,
    },
    {
      key: "commissionRate",
      label: "Commission Rate",
      entity: "dealer",
      group: "Financial",
      data_type: "percentage",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: false,
      width: 120,
    },
    {
      key: "city",
      label: "City",
      entity: "dealer",
      group: "Contact",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: false,
      width: 150,
    },
    {
      key: "createdAt",
      label: "Created Date",
      entity: "dealer",
      group: "System",
      data_type: "date",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
  ],
  deal: [
    {
      key: "tid",
      label: "TID",
      entity: "deal",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 100,
    },
    {
      key: "dealCode",
      label: "Deal Code",
      entity: "deal",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "title",
      label: "Title",
      entity: "deal",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf", "word"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 250,
    },
    {
      key: "client",
      label: "Client",
      entity: "deal",
      group: "Relationships",
      data_type: "relation",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: false,
      default_visible: true,
      width: 200,
      relation_path: "client.name",
      format: (v) => v?.name || "",
    },
    {
      key: "dealAmount",
      label: "Amount",
      entity: "deal",
      group: "Financial",
      data_type: "currency",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
    {
      key: "stage",
      label: "Stage",
      entity: "deal",
      group: "Status",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
    {
      key: "status",
      label: "Status",
      entity: "deal",
      group: "Status",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf", "word"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "dealType",
      label: "Type",
      entity: "deal",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "dealDate",
      label: "Deal Date",
      entity: "deal",
      group: "System",
      data_type: "date",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
    {
      key: "createdAt",
      label: "Created Date",
      entity: "deal",
      group: "System",
      data_type: "date",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
  ],
  employee: [
    {
      key: "tid",
      label: "TID",
      entity: "employee",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 100,
    },
    {
      key: "employeeId",
      label: "Employee ID",
      entity: "employee",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "name",
      label: "Name",
      entity: "employee",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf", "word"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 200,
    },
    {
      key: "email",
      label: "Email",
      entity: "employee",
      group: "Contact",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel"],
      roles: ["admin", "hr_manager"],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 200,
    },
    {
      key: "phone",
      label: "Phone",
      entity: "employee",
      group: "Contact",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel"],
      roles: ["admin", "hr_manager"],
      filterable: true,
      sortable: true,
      default_visible: false,
      width: 150,
    },
    {
      key: "department",
      label: "Department",
      entity: "employee",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
    {
      key: "position",
      label: "Position",
      entity: "employee",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
    {
      key: "status",
      label: "Status",
      entity: "employee",
      group: "Status",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf", "word"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "joinDate",
      label: "Join Date",
      entity: "employee",
      group: "System",
      data_type: "date",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
    {
      key: "salary",
      label: "Salary",
      entity: "employee",
      group: "Financial",
      data_type: "currency",
      exportable: true,
      formats: ["csv", "excel"],
      roles: ["admin", "hr_manager"],
      filterable: true,
      sortable: true,
      default_visible: false,
      width: 150,
    },
    {
      key: "createdAt",
      label: "Created Date",
      entity: "employee",
      group: "System",
      data_type: "date",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: false,
      width: 150,
    },
  ],
  voucher: [
    {
      key: "voucherNumber",
      label: "Voucher #",
      entity: "voucher",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf", "word"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
    {
      key: "type",
      label: "Type",
      entity: "voucher",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf", "word"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 100,
    },
    {
      key: "date",
      label: "Date",
      entity: "voucher",
      group: "System",
      data_type: "date",
      exportable: true,
      formats: ["csv", "excel", "pdf", "word"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "status",
      label: "Status",
      entity: "voucher",
      group: "Status",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf", "word"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "amount",
      label: "Amount",
      entity: "voucher",
      group: "Financial",
      data_type: "currency",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
    {
      key: "description",
      label: "Description",
      entity: "voucher",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: false,
      default_visible: true,
      width: 300,
    },
    {
      key: "paymentMethod",
      label: "Payment Method",
      entity: "voucher",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: false,
      width: 150,
    },
    {
      key: "referenceNumber",
      label: "Reference #",
      entity: "voucher",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel"],
      roles: [],
      filterable: true,
      sortable: false,
      default_visible: false,
      width: 150,
    },
    {
      key: "createdAt",
      label: "Created Date",
      entity: "voucher",
      group: "System",
      data_type: "date",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: false,
      width: 150,
    },
    {
      key: "id",
      label: "ID",
      entity: "voucher",
      group: "System",
      data_type: "string",
      exportable: false,
      formats: [],
      roles: [],
      filterable: false,
      sortable: false,
      default_visible: false,
    },
  ],
  property: [
    {
      key: "tid",
      label: "TID",
      entity: "property",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 100,
    },
    {
      key: "propertyCode",
      label: "Property Code",
      entity: "property",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "name",
      label: "Name",
      entity: "property",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf", "word"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 200,
    },
    {
      key: "type",
      label: "Type",
      entity: "property",
      group: "Basic",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "status",
      label: "Status",
      entity: "property",
      group: "Status",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf", "word"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 120,
    },
    {
      key: "city",
      label: "City",
      entity: "property",
      group: "Contact",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: false,
      width: 150,
    },
    {
      key: "address",
      label: "Address",
      entity: "property",
      group: "Contact",
      data_type: "string",
      exportable: true,
      formats: ["csv", "excel"],
      roles: [],
      filterable: true,
      sortable: false,
      default_visible: false,
      width: 300,
    },
    {
      key: "totalUnits",
      label: "Total Units",
      entity: "property",
      group: "Basic",
      data_type: "number",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: false,
      width: 120,
    },
    {
      key: "createdAt",
      label: "Created Date",
      entity: "property",
      group: "System",
      data_type: "date",
      exportable: true,
      formats: ["csv", "excel", "pdf"],
      roles: [],
      filterable: true,
      sortable: true,
      default_visible: true,
      width: 150,
    },
  ],
};

/**
 * Get columns for an entity
 */
export function getEntityColumns(entity: string): EntityColumnDefinition[] {
  return ENTITY_COLUMN_REGISTRY[entity] || [];
}

/**
 * Get exportable columns for an entity, filtered by format and role
 */
export function getExportableColumns(
  entity: string,
  format: ExportFormat,
  userRoles: string[] = []
): EntityColumnDefinition[] {
  const all = getEntityColumns(entity);
  return all.filter((col) => {
    if (!col.exportable) return false;
    if (!col.formats.includes(format)) return false;
    if (col.roles.length > 0 && !col.roles.some((r) => userRoles.includes(r))) return false;
    return true;
  });
}

/**
 * Get columns grouped by group
 */
export function getColumnsByGroup(
  entity: string,
  format?: ExportFormat,
  userRoles: string[] = []
): Record<ColumnGroup, EntityColumnDefinition[]> {
  const cols = format
    ? getExportableColumns(entity, format, userRoles)
    : getEntityColumns(entity);
  const grouped: Record<string, EntityColumnDefinition[]> = {};
  for (const col of cols) {
    if (!grouped[col.group]) grouped[col.group] = [];
    grouped[col.group].push(col);
  }
  return grouped as Record<ColumnGroup, EntityColumnDefinition[]>;
}

/**
 * Get default visible columns for table rendering
 */
export function getDefaultVisibleColumns(entity: string): EntityColumnDefinition[] {
  return getEntityColumns(entity).filter((col) => col.default_visible);
}

/**
 * Format column value for display/export
 */
export function formatColumnValue(
  col: EntityColumnDefinition,
  value: any,
  row?: any
): string {
  if (col.format) return col.format(value, row);
  if (value == null) return "";
  if (col.data_type === "date") {
    if (value instanceof Date) return value.toISOString().split("T")[0];
    if (typeof value === "string") {
      try {
        return new Date(value).toISOString().split("T")[0];
      } catch {
        return value;
      }
    }
    return String(value);
  }
  if (col.data_type === "boolean") {
    return value === true || value === "true" || value === 1 ? "Yes" : "No";
  }
  if (col.data_type === "currency") {
    const num = typeof value === "string" ? parseFloat(value) : value;
    return isNaN(num) ? "" : `Rs ${num.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  }
  if (col.data_type === "percentage") {
    const num = typeof value === "string" ? parseFloat(value) : value;
    return isNaN(num) ? "" : `${num}%`;
  }
  if (col.data_type === "relation" && col.relation_path && typeof value === "object") {
    const parts = col.relation_path.split(".");
    let v = value;
    for (const p of parts) {
      v = v?.[p];
      if (v == null) break;
    }
    return v != null ? String(v) : "";
  }
  return String(value);
}
